# Uncomment the next line to define a global platform for your project
platform :ios, '15.2'

target 'BeyableiOS' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!
pod 'BeyableClient'

  # Pods for BeyableiOS

end
